title: Tatiana Gabel
logo: "1709892525258.jpg?raw=true"
description: >
  Software Developer
  <br><br>
  Colorado State University Computer and Data Science
  <br><br>
  <a href="https://www.linkedin.com/in/tiana-gabel/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # TBD Google Analytics tracking ID here
